In [17]:
import numpy as np
import open3d as o3d
import os
import glob
from data_understanding import read_meta_data,save_meta_data

In [ ]:
# map_building = glob.glob("map**")
# ins_building = glob.glob("building**")
# """
# for editing the bug
# """
# for i in map_building:
#     area_json = i.split("map_ins_")[-1]
#     os.rename(i,f"building_ins_{area_json}")

# for i,_ in enumerate(map_building):
#     dict = read_meta_data(map_building[i])
#     dict.pop("building")
#     area_json = map_building[i].split("ins_")[-1]
#     building = read_meta_data(f"building_ins_{area_json}")
#     dict["building"]=building
#     os.remove(f"building_ins_{area_json}")
#     os.remove(map_building[i])
#     save_meta_data(area_json[:-5],dict)
area_meta_data_json= glob.glob("T**.json")
for num in range(len(area_meta_data_json)):
    map_ins = read_meta_data(area_meta_data_json[num])
    for k,kd in enumerate(map_ins["building"].keys()):
        path_all_data = map_ins["building"][kd]["path_all_data_txt"]
        print(path_all_data)
        path_all_data_txt = path_all_data[:-4]+".txt"
        print(path_all_data_txt)
        all_data = np.loadtxt(path_all_data)
        np.savetxt(path_all_data_txt,all_data,fmt="%.9f %.9f %.9f %d %d %d")
        # map_ins[id_keys[-1]][kd].pop("path_all_data_txt")
        map_ins["building"][kd]["path_all_data_txt"] = path_all_data_txt
        os.remove(path_all_data)
        
    save_meta_data(area_meta_data_json[0][:-5],map_ins)
    


In [96]:
area_meta_data_json= glob.glob("T**.json")

In [97]:
area_meta_data = read_meta_data(area_meta_data_json[0])

In [2]:
import numpy as np
import open3d as o3d

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [32]:
test = np.loadtxt("GOINGTOTHESIS/all_data_building/T_315500_233500_NE_T_315500_234000_SE/building_000.txt")
test[:,:3] = stats.(test[:,:3])
test[:,3:]=test[:,3:]/255*2

In [7]:
pcd = o3d.io.read_point_cloud("/media/nmhlog/BackUp Windows/Thesis/GOINGTOTHESIS/Dataset/T_315500_233500_NE_T_315500_234000_SE/building_01.txt",format='xyz')

In [44]:
pcd = o3d.geometry.PointCloud()

In [45]:
pcd.points = o3d.utility.Vector3dVector(test[:,:3])

array([[ 1.33125623, -0.36010444, -1.5927004 ],
       [ 1.23736297, -0.52526804, -2.45545154],
       [ 1.3357074 , -0.39526757, -1.59831114],
       ...,
       [ 1.34828544, -0.84311061, -1.57811288],
       [ 1.38004847, -0.83486388, -1.40562676],
       [ 1.38487186, -0.82146295, -1.51655654]])

In [53]:
min(np.array(pcd.points))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [58]:
test = np.array(pcd.points)-np.min(test[:,:3])

In [59]:
test

array([[ 1.33125623, -0.36010444, -1.5927004 ],
       [ 1.23736297, -0.52526804, -2.45545154],
       [ 1.3357074 , -0.39526757, -1.59831114],
       ...,
       [ 1.34828544, -0.84311061, -1.57811288],
       [ 1.38004847, -0.83486388, -1.40562676],
       [ 1.38487186, -0.82146295, -1.51655654]])

In [47]:
downpcd = pcd.voxel_down_sample(voxel_size=0.05)
o3d.visualization.draw_geometries([downpcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

In [ ]:
pcd.points

In [46]:
pcd.get_center()

array([ 1.95436250e-12, -2.91133653e-12, -2.11765940e-13])

In [49]:
pcd.compute_point_cloud_distance(pcd.get_center())

TypeError: compute_point_cloud_distance(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cpu.pybind.geometry.PointCloud, target: open3d.cpu.pybind.geometry.PointCloud) -> open3d.cpu.pybind.utility.DoubleVector

Invoked with: PointCloud with 208827 points., array([ 1.95436250e-12, -2.91133653e-12, -2.11765940e-13])