In [2]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tqdm
import json
import glob
from numpyencoder import NumpyEncoder
import re

In [3]:
import open3d
import shutil

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [26]:
# for i in tqdm.tqdm(glob.glob("/media/nmhlog/Naufal Disk/Dataset/T_315500_233500_NE_T_315500_234000_SE/**.json")):
#     print(i)
#     shutil.copyfile(i, "/".join(i.split("/")[4:]))

100%|██████████| 1/1 [00:00<00:00, 89.01it/s]

/media/nmhlog/Naufal Disk/Dataset/T_315500_233500_NE_T_315500_234000_SE/meta_data.json


In [17]:
# for i in tqdm.tqdm(glob.glob("/media/nmhlog/Naufal Disk/Dataset/**/**.txt")):
#     shutil.copyfile(i, "/".join(i.split("/")[4:]))

100%|██████████| 38038/38038 [1:02:02<00:00, 10.22it/s] 


In [18]:
# for i in tqdm.tqdm(glob.glob("/media/nmhlog/Naufal Disk/Dataset/**/**.json")):
#     shutil.copyfile(i, "/".join(i.split("/")[4:]))

100%|██████████| 13/13 [00:00<00:00, 57.89it/s]


In [7]:
# for i in tqdm.tqdm(glob.glob("/media/nmhlog/Naufal Disk/Dataset/T_316000_233500_NE_T_316000_233500_SW/**.txt")):
#     shutil.copyfile(i, "/".join(i.split("/")[4:]))
# for i in tqdm.tqdm(glob.glob("/media/nmhlog/Naufal Disk/Dataset/T_316000_233500_NE_T_316000_233500_SW/**.json")):
#     shutil.copyfile(i, "/".join(i.split("/")[4:]))
# for i in glob.glob(f"{PATH}/**/b**.txt"):
#     os.remove(i)

100%|██████████| 1/1 [00:00<00:00, 89.83it/s]


In [19]:
PATH="Dataset"
METADATA= glob.glob(f"{PATH}/**/**.json")

In [7]:
folder_name = [i.split("/")[1] for i in glob.glob(f"{PATH}/**/")]
existing_metadata = [i.split("/")[1] for i in METADATA]

In [8]:
for n_folder in folder_name:
    if n_folder not in existing_metadata:
        print(n_folder) 

In [20]:
def save_meta_data(file_name,dict_file):
    with open(f'{file_name}.json', 'w') as fp:
        json.dump(dict_file, fp,  indent=4,cls=NumpyEncoder)

def read_meta_data (path):
    with open(path, 'r') as j:
        contents = json.loads(j.read())
        return contents
        
def del_data(files_name,folder_name="Dataset"):
    try:
        for d in files_name:
            os.remove(f"{folder_name}/{d}")
    except:
        os.remove(f"{folder_name}/{files_name}")

In [12]:
METADATA

['Dataset/T_315500_234500_SW/meta_data.json',
 'Dataset/T_316000_233500_NE_T_316000_233500_SW/meta_data.json',
 'Dataset/T_316000_233500_NW/meta_data.json',
 'Dataset/T_316000_233500_SE/meta_data.json',
 'Dataset/T_316000_234000_NE/meta_data.json',
 'Dataset/T_316000_234000_NW/meta_data.json',
 'Dataset/T_316000_234000_SE/meta_data.json',
 'Dataset/T_316000_234000_SW/meta_data.json',
 'Dataset/T_316500_234000_SW_T_316500_233500_NW/meta_data.json']

In [13]:
METADATA = METADATA[5:]

In [21]:
b_data = [i.split("/")[1] for i in METADATA]
for b_d in b_data :
    buff = glob.glob(f"{PATH}/{b_d}/**.txt")
    data = np.array([i.split("/") for i in buff if "building" in i or "buidling" in i])
    new= data[:,-1].copy()
    new = [i.split("_") for i in new]
    for i,_ in enumerate(new):
        if len(new[i])==2:
            new[i][1] = new[i][1].split(".")
            new[i][1][0]= new[i][1][0].zfill(3)
            new[i][1]= ".".join(new[i][1])
        else:
            new[i][1]=new[i][1].zfill(3)
        new[i]= "_".join(new[i])
    index = np.where(data[:,-1]!=new)[0]
    if index.size != 0:
        old_data= data[:,-1]
        METADATA_buff = read_meta_data(f'{PATH}/{b_d}/meta_data.json')
        OLD_METADATA_buff = METADATA_buff.copy()
        for i in index:
            try:
                data_edited= METADATA_buff.pop(old_data[i][:-4])
            except:
                continue
            list_new_data=new[i].split("/")
            METADATA_buff[list_new_data[-1][:-4]]={
                                                    "path":f"{b_d}/{new[i]}",
                                                    "jumlah_point":data_edited["jumlah_point"]
                                                    }

        print(index)
        save_meta_data(f'{PATH}/{b_d}/meta_data',METADATA_buff)
        for idx in index:
            os.rename(f"{PATH}/{b_d}/{old_data[idx]}",f"{PATH}/{b_d}/{new[idx]}")
        #     # print()
        #     # print(old_data)
# METADATA= glob.glob(f"{PATH}/**/**.json")

[   0    1    2 ... 1600 1601 1602]
[   0    1    2 ... 3038 3039 3040]
[   0    1    2 ... 2656 2657 2658]
[   0    1    2 ... 1397 1398 1399]
[   0    1    2 ... 4098 4099 4100]
[   0    1    2 ... 2544 2545 2546]
[   0    1    2 ... 1693 1694 1695]
[   0    1    2 ... 3741 3742 3743]
[   0    1    2 ... 2904 2905 2906]
[   0    1    2 ... 2907 2908 2909]
[   0    1    2 ... 2734 2735 2736]


In [22]:
def get_list_per_instace(str_name ,file_list,Area,dict_file):
    result_dict = {}
    id_ns = np.unique(np.array([b.split("_")[1] for b in dict_file],dtype="int16"))
    zf = 3 #if Area ==  "T_316000_233500_NE_T_316000_233500_SW" or Area=="T_315500_234500_SE" else 2
    for idn in id_ns :
        r = re.compile(f"{str_name}_{str(idn).zfill(zf)}")
        result_dict[f"{str_name}_{str(idn).zfill(zf)}"] = list(filter(r.match, file_list)) 
    return result_dict

for i,_ in tqdm.tqdm(enumerate(METADATA),total=len(METADATA)):
    Area = METADATA[i].split("/")[1]
    md = read_meta_data(METADATA[i])
    file_names = md.keys()
    building,ground,undefined,vegetation=[],[],[],[]
    label = set([i.split("_")[0] for i in file_names])
    for fn in file_names:
        if 'building' in fn.lower() or "buidling" in fn.lower():
            building.append(fn)
        if 'ground' in fn.lower():
            ground.append(fn)
        if 'undefined' in fn.lower() or "undifined" in fn.lower() or "undefined" in fn.lower() or 'Undefined' in fn.lower():
            undefined.append(fn)
        if 'vegetation'in fn.lower():
            vegetation.append(fn)
    dict_area={
        "building":get_list_per_instace(str_name = "building",file_list = building,dict_file=building,Area=Area),
        "vegetation":vegetation,
        "ground":ground,
        "undefined":undefined
        }
    save_meta_data(f"map_ins_{Area}",dict_area)

def maping_meta_data(class_name,map_data,meta_data):
    inst_id = {}
    try:
        for count,key in enumerate(map_data[class_name]):
            try:
                k_split = key.split("_")
                if len(k_split)==3:
                    _,sub_class,key_id = k_split
                else :
                    sub_class,key_id[:-4] = k_split
            except:
                sub_class,key_id=key,0
                
            inst_id[str(count).zfill(3)]={
                "total_point": meta_data[key]["jumlah_point"],
                "path": meta_data[key]["path"],
                "sub_class": sub_class,
                "id": str(int(key_id)-1).zfill(3)
                }
    except Exception as e:
        print(class_name)
        print(meta_data[class_name])
        inst_id["000"]={
            "total_point": meta_data[class_name]["jumlah_point"],
            "path": meta_data[class_name]["path"],
            "sub_class": "000",
            "id": "000"
            }
    return inst_id
    
def map_to_inst(map_data_json,meta_data_json):
    map_data = read_meta_data(map_data_json)
    meta_data= read_meta_data(meta_data_json)
    for k in map_data.keys():
        if k == "building":
            inst_id_building = {}
            list_build_id= list(map_data[k].keys())
            for id_b in list_build_id:
                id_ins = str(int(id_b.split("_")[-1])-1).zfill(3)
                total_point = sum([meta_data[i]["jumlah_point"] for i in map_data[list(map_data.keys())[0]][id_b]])
                list_all_txt = [meta_data[i]["path"] for i in map_data[list(map_data.keys())[0]][id_b]]
                inst_id_building[id_ins]={
                    "total_point":total_point,
                    "path":list_all_txt
                    }
        elif k=="vegetation" :
            inst_id_vegetation = maping_meta_data("vegetation",map_data,meta_data)
        elif k=="ground" :
            inst_id_ground = maping_meta_data("ground",map_data,meta_data)
        else :
            inst_id_undefined = maping_meta_data("undefined",map_data,meta_data)
    return [inst_id_building,inst_id_vegetation,inst_id_ground,inst_id_undefined]

for i,_ in enumerate(METADATA):
    area=METADATA[i].split("/")[1]
    ins = map_to_inst(f"map_ins_{area}.json",METADATA[i])
    save_meta_data(f"map_ins_{area}",{"building":ins[0],"vegetation":ins[1],"ground":ins[2],'undefined':ins[3]})

100%|██████████| 13/13 [00:01<00:00, 12.71it/s]


In [23]:
MAPTOINST_META_LIST= glob.glob("map_**")
def get_combining_building_data(map_data_json = MAPTOINST_META_LIST,buff_folder="Dataset") :   
    for i,meta_name in tqdm.tqdm(enumerate(map_data_json),total=13):
        map_data = read_meta_data(map_data_json[i])["building"]
        buff_folder = f"all_data_building/{map_data_json[i][8:-5]}"
        os.makedirs(buff_folder,exist_ok=True)
        map_data_id= list(map_data.keys())
        for mdi in map_data_id:
            list_data_txt = map_data[mdi]["path"]
            # Start from init = 0 and append until last
            all_data = np.loadtxt(f"Dataset/{list_data_txt[0]}")[:,:6]
            for idx in range(1,len(list_data_txt)):
                try:
                    buff = np.loadtxt(f"Dataset/{list_data_txt[idx]}")[:,:6]
                    all_data = np.append(all_data,buff,axis=0)
                except :
                    buff = np.loadtxt(f"Dataset/{list_data_txt[idx]}")[:6]
                    all_data = np.append(all_data,[buff],axis=0)
            del_data(list_data_txt)
            if "T_316000_233500_NE_T_316000_233500_SW" in meta_name:
                data_building_index = np.where(all_data[:,0]<318000)
                data_bulding_sub_building_index = np.where(all_data[:,0]>318000)
                data_building = all_data[data_building_index]
                data_bulding_sub_building = all_data[data_bulding_sub_building_index]
                data_bulding_sub_building[:,0] = data_bulding_sub_building[:,0]-2000
                data_bulding_sub_building[:,1] = data_bulding_sub_building[:,1]-3619
                data_bulding_sub_building[:,2] = data_bulding_sub_building[:,2]+40
                all_data = np.append(data_building,data_bulding_sub_building,axis=0)
            save_txt_loc = f"{buff_folder}/building_{mdi}.txt"
            map_data[mdi]["path"] = save_txt_loc
            np.savetxt(save_txt_loc,all_data,fmt='%.8f %.8f %.8f %d %d %d')
        old_map = read_meta_data(map_data_json[i])
        old_map["building"]= map_data
        save_meta_data(f"{map_data_json[i][8:-5]}",old_map)
        os.remove(f"{map_data_json[i]}")
get_combining_building_data()

100%|██████████| 13/13 [42:57<00:00, 198.25s/it]


In [ ]:


np.savetxt("all_data_building/T_315500_234500_SW/building_065.txt",all_data,fmt='%.8f %.8f %.8f %d %d %d')


In [50]:
# list_data_txt = map_data[mdi]["path"]
data = glob.glob("Dataset/T_315500_234500_SW/b**")
all_data = np.loadtxt(data[0])[:,:6]

for i in data[1:]:
    # for idx in range(1,len(list_data_txt)):
    print(i)
    # try:
    buff = np.loadtxt(i)[:,:6]
    all_data = np.append(all_data,buff,axis=0)
    # except :
    #     buff = np.loadtxt(i)[:6]
    #     all_data = np.append(all_data,[buff],axis=0)

Dataset/T_315500_234500_SW/building_66_roof_01.txt
Dataset/T_315500_234500_SW/building_66_window_01.txt
Dataset/T_315500_234500_SW/building_66_window_02.txt
Dataset/T_315500_234500_SW/building_66_window_03.txt
Dataset/T_315500_234500_SW/building_66_window_04.txt
Dataset/T_315500_234500_SW/building_66_window_05.txt
Dataset/T_315500_234500_SW/building_66_window_06.txt
Dataset/T_315500_234500_SW/building_66_window_07.txt
Dataset/T_315500_234500_SW/building_66_window_08.txt
Dataset/T_315500_234500_SW/building_66_window_09.txt
Dataset/T_315500_234500_SW/building_66_window_10.txt
Dataset/T_315500_234500_SW/building_66_window_11.txt
Dataset/T_315500_234500_SW/building_66_window_12.txt
Dataset/T_315500_234500_SW/building_66_window_13.txt
Dataset/T_315500_234500_SW/building_66_window_14.txt
Dataset/T_315500_234500_SW/building_66_window_15.txt
Dataset/T_315500_234500_SW/building_66_window_16.txt
Dataset/T_315500_234500_SW/building_66_window_17.txt


In [52]:
len(all_data)

50250

In [43]:
len(np.loadtxt("Dataset/T_315500_234500_SW/building_66_roof_01.txt")[:,:6])

40451

In [36]:
i

'Dataset/T_315500_234500_SW/building_66_window_17.txt'